GET https://pro-api.coinmarketcap.com/v2/tools/price-conversion?amount=50&id=1&convert=USD
Accept: application/json
X-CMC_PRO_API_KEY: 320c56fe-4b4a-4b03-8481-87620269aebb

###
GET https://pro-api.coinmarketcap.com/v1/cryptocurrency/map
Accept: application/json
X-CMC_PRO_API_KEY: 320c56fe-4b4a-4b03-8481-87620269aebb

###
GET https://pro-api.coinmarketcap.com/v1/fiat/map
Accept: application/json
X-CMC_PRO_API_KEY: 320c56fe-4b4a-4b03-8481-87620269aebb