protocol_http:
  url:
    url_get_fiat: "https://pro-api.coinmarketcap.com/v1/fiat/map"
    url_get_cryptocurrencies: "https://pro-api.coinmarketcap.com/v1/cryptocurrency/map"
    url_convert_one_to_one: "https://pro-api.coinmarketcap.com/v2/tools/price-conversion"